app:
  profiles:
    env: loc
    app_name: user-srv
  etcd:
    enabled: true
    host: 127.0.0.1
    port: 2379
  mysql:
    enabled: true
    url: root:root@(47.106.183.226:3306)/go-mirco?charset=utf8&parseTime=true&loc=Asia%2FShanghai
    maxIdleConnection: 100
    maxOpenConnection: 130
    connMaxLifetime: 100