app:
  mysql:
    enabled: true
    url: root:Yao1127056420.@(47.106.183.226:3306)/micro_book_mall?charset=utf8&parseTime=true&loc=Asia%2FShanghai
    maxIdleConnection: 100
    maxOpenConnection: 130
    connMaxLifetime: 100